### ISSUE TITLE
Transmission data Schott filters

### ISSUE THREAD

**Issue by VincentVandalon** [polyanskiy/refractiveindex.info-database#13]
Do we also want transmission data of Schott filters such as OG515 and so on?

If so, do we go for the tabulated data published by Schott (which is an average over many fabrication runs) or transmission data available of recent filters? For the latter I have tabulated data, the former I would have to digitize from the data sheets. 

I would be willing to do either.

**Comment by polyanskiy** [comment]
This would be a great addition to the database! I generally prefer well documented / published data. In this case this is probably data published by Schott.

**Comment by VincentVandalon** [comment]
I just realized, Schott only publishes the internal transmission data (from which I can calculate k) and the refractive index (real part) at 3 wavelengths. Might be still better than no data.

http://www.schott.com/advanced_optics/english/download/schott-bandpass-bg40-may-2016-en.pdf
