### ISSUE TITLE
malformed fields in database

### ISSUE THREAD

**Issue by tjconstant** [polyanskiy/refractiveindex.info-database#22]
Hi!

While reading the database into R, I found two small errors that caused the parsing to fail:

- an extra (empty) "content:" field in "OHARA - NBH (Niobate, high-index)"
- A duplicated "info:" key in Cs pointing to Cu

I don't think these are intentional and are indeed errors, but I might be wrong. I've fixed these in a fork, happy to provide a pull-request if you'd like.

**Comment by polyanskiy** [comment]
Fixed
thank you!
