### ISSUE TITLE
Inconsistent Data Type "thermal-conductivity" in IRG27 Schott glass

### ISSUE THREAD

**Issue by VVKris** [polyanskiy/refractiveindex.info-database#26]
The property "thermal_conductivity" in [IRG27](https://github.com/polyanskiy/refractiveindex.info-database/blob/master/database/data/glass/schott/infrared/IRG27.yml) is sequence of a mapping with two mapping keys : "temperature" and "value". On the contrary, in [IRG22](https://github.com/polyanskiy/refractiveindex.info-database/blob/master/database/data/glass/schott/infrared/IRG22.yml), [IRG24](https://github.com/polyanskiy/refractiveindex.info-database/blob/master/database/data/glass/schott/infrared/IRG24.yml), [IRG25](https://github.com/polyanskiy/refractiveindex.info-database/blob/master/database/data/glass/schott/infrared/IRG25.yml), [IRG26](https://github.com/polyanskiy/refractiveindex.info-database/blob/master/database/data/glass/schott/infrared/IRG26.yml), the property "thermal_conductivity" is simply a scalar map. This leads to difficulty in creating a single parsing schema for the entire database.

**Comment by polyanskiy** [comment]
fixed!
