### ISSUE TITLE
Formatting error in data\main\ZnS\Amotchkina.yml

### ISSUE THREAD

**Issue by danielbacon-brown** [polyanskiy/refractiveindex.info-database#28]
In data\main\ZnS\Amotchkina.yml, line 7 reads:
degrees"
which causes parsing to fail.
Removing line 7 fixes the problem.

**Comment by polyanskiy** [comment]
I don't see this line in data\main\ZnS\Amotchkina.yml
Line 7 is "DATA:"

**Comment by danielbacon-brown** [comment]
Oh my bad.  I was looking at the 2020-01-19 release.  It's already fixed in the latest version.
Thanks.
