### ISSUE TITLE
Sellmeier for ZBLAN?

### ISSUE THREAD

**Issue by jmmelko** [polyanskiy/refractiveindex.info-database#31]
Hi,

I may be wrong but I think there aren't data available for fluorozirconate glass such as ZBLAN

Indeed the fibered material is different from the bulk due to differences in density and stress, and there is probably a lot of variation from manufacturer to manufacturer, but I thought that maybe, at least, the Sellmeier reported by F. Gan in 1999 could be included (https://doi.org/10.1016/0022-3093(94)00592-3).

Please tell me if it's OK if I do it.

The glass would belong to the Main(Inorganic)/Fluoride category, I think.

Another set of Sellemeirs is published by Thorlabs at: https://www.thorlabs.de/newgrouppage9.cfm?objectgroup_id=7999

**Comment by polyanskiy** [comment]
Thank you!
Gan's dispersion formula for ZBLAN added: https://refractiveindex.info/?shelf=glass&book=ZBLAN&page=Gan
