### ISSUE TITLE
Missordering on sellmeier Coefficients

### ISSUE THREAD

**Issue by hhartwell** [polyanskiy/refractiveindex.info-database#37]
Hello, just want to start by saying my team and I are super appreciative of this repo and all the work that went into creating it. This is a massive accomplishment and wonderful contribution. I would be super happy to lend a helping hand to this bug.

I am noticing that certain glass materials do not keep a consistent ordering to their formula coefficients. the examples i found were in the schott folder

Here, f5 is in an order that follows a pattern of
`b1, c1, b2, c2, b3, c3,`
Then k10 seems to break this pattern and go
`c1, b1, b2, c2, b3, c3`
Here are some graphs that compare these two glasses and their resulting refractive index calculations. In these examples, the coefficients are pulled to match the k10 ordering. the blue line corresponds to data gathered from the refractive_index_db, and the red line corresponds to data our team has compiled

![K10](https://user-images.githubusercontent.com/26777224/149024328-32342a5e-1bbc-4947-b706-af007a2eff50.png)
![F5](https://user-images.githubusercontent.com/26777224/149024343-b48be08f-007a-4042-880e-64e8892816b7.png)

**Comment by polyanskiy** [comment]
Hi!

how exactly did you get the coefficients from the database? Everything seems to be working fine with the web-interface:

https://refractiveindex.info/?shelf=glass&book=SCHOTT-K&page=K10
coefficients: 0 1.15687082 0.00809424251 0.0642625444 0.0386051284 0.872376139 104.74773

https://refractiveindex.info/?shelf=glass&book=SCHOTT-F&page=F5
coefficients: 0 1.3104463 0.00958633048 0.19603426 0.0457627627 0.96612977 115.011883

**Comment by hhartwell** [comment]
Oh my goodness thank you so much for the reply! we are pulling directly from the yml file into a list, and zipping them up with a predefined coefficient ordering. the files i have reflect exactly what you pasted. . . . i will close the issue and dig further into the bug we are dealing with and double check that the problem is on our side. 

Again, thank you so much! We cannot emphasize enough how grateful we are to your work!
