### ISSUE TITLE
Raman spectra

### ISSUE THREAD

**Issue by FilipDominec** [polyanskiy/refractiveindex.info-database#42]
Hi, first let me thank you for all effort you put in the useful website.

I suggest that Raman spectroscopic data could be added as a separate database (like the "n₂ spectra" are now). There are some open-sourced spectra here on github (e.g. https://github.com/sutapaghosal/Raman-Spectral-Website/tree/master/Spectra with a simple browser https://cdph-ramanspectroscopywebsite.github.io/CDPH-Raman-Microspectroscopy-Website/spectraldata.html, or https://github.com/whenfung/Raman-spectra/tree/master/data/%E8%AF%95%E5%89%82%E6%A0%87%E5%87%86%E5%93%81%E8%B0%B1%E5%9B%BE). 

Our laboratory could contribute with some high-quality Raman entries for technologically important materials like semiconductors. 

Also there exist some limited resources on complex permittivity spectra, part of which I tried to document here: https://www.fzu.cz/~dominecf/eps/ When such data are available, they allow to design very realistic materials for the https://github.com/NanoComp/meep FDTD simulation. Also one can use permittivity directly compute and verify the **n** and **k** quantities. 

Do you think these new two "libraries" would be a viable extension?

**Comment by polyanskiy** [comment]
Hi!

Thank you for reaching out and apologies for the delayed reply.

Your suggestion of adding a Raman spectra database is indeed intriguing. I'm open to incorporating a user interface for it on the RefractiveIndex.INFO website. However, my current time constraints limit me from investing significant effort into constructing the database itself. If you're prepared to undertake the primary work of assembling the database, I wholeheartedly encourage you to do so! There are two main prerequisites:
1) The database should utilize a YAML-based file format akin to the ones used in the 'nk' and 'n2' databases.
2) The source for all data must be meticulously documented. Ideally, data from peer-reviewed journals would be favored.

Regarding complex permittivity data: this can be translated into n,k values and subsequently incorporated into the 'nk' database. The same standards for data traceability apply in this context as well.

I appreciate your commitment and the resources you've shared. Looking forward to potential collaboration!

Best regards,
Misha

**Comment by FilipDominec** [comment]
If there is enough time, I will try to assemble some Raman data and make a PR. 

Another idea I got using refractiveindex.info is that most often I am interested in *all* n,k spectra for a given material at once. If they don't overlap, they give a wider spectral range, if they do overlap, they at least give an estimate of accuracy. 

This behaviour was already implemented for the n₂ data, where one can (un)select the datasets to be shown simultaneously. Do you think this could be done for the "n,k" data as well? Perhaps the "Page" combo box could allow multiple selection?

**Comment by polyanskiy** [comment]
Please take a look at the nkexplorer.py script located in the 'tools' sub-folder. It should accomplish what you're looking for.
