### ISSUE TITLE
Typo in the Abbe diagram

### ISSUE THREAD

**Issue by Lexachoc** [polyanskiy/refractiveindex.info-database#43]
I think this should be `Abbe diagram`

![image](https://github.com/polyanskiy/refractiveindex.info-database/assets/20377719/0ffcd8fe-cf08-431c-a847-0f054f0b7c02)

![image](https://github.com/polyanskiy/refractiveindex.info-database/assets/20377719/e358bf1e-53b5-46f2-b2dc-1b0f87afbd34)

### ---------------
P.S. A big thank you for your work on this database, 10 years ago I visited this website in an Optics course to solve some refractive index exercises. Today I magically came across this website, and in this moment I realized how incredible this work is to maintain it for over 10 years! 

I have created a web glass database (https://sciglass.uni-jena.de/). I think your website will be a good resource for people interested in the refractive index of glass (https://refractiveindex.info/?shelf=glass). In the future, I will put your website link as an external resource for refractive index.
 
There are over 15,000 optical spectra in the SciGlass database, most of them are `Transmittance` and `Absorption` (it seems that `Reflection` and `Complex refractive index` spectra are not stored.) Although these refractive index data are not stored as spectral data, they are stored as standardized properties:
![image](https://github.com/polyanskiy/refractiveindex.info-database/assets/20377719/dcb8c68c-9463-4332-b50d-9f90c7a02a95)

However, the SciGlass database stores only few commercial glass, I think [INTERGLAD](https://www.newglass.jp/interglad_n/gaiyo/info_e.html) has a lot such data.

**Comment by polyanskiy** [comment]
Wow, this typo must have been there from the very beginning – for nearly 15 years. Thank you for spotting it and reporting it! SciGlass seems to be an incredible resource for optics-related R&D!
