### ISSUE TITLE
Duplicate page "Taylor"

### ISSUE THREAD

**Issue by AmosEgel** [polyanskiy/refractiveindex.info-database#44]
The reference to Taylor's diamond data appears twice, once [here](https://github.com/polyanskiy/refractiveindex.info-database/blob/9238624ec5c2001bf288b84a28fd33549e75f1e6/database/catalog-nk.yml#L622) and once [here](https://github.com/polyanskiy/refractiveindex.info-database/blob/9238624ec5c2001bf288b84a28fd33549e75f1e6/database/catalog-nk.yml#L632). In one case, the key-word "film" is added, but both entries refer to the same data.

By the way, this repository is very handy, great work, thanks a lot for keeping this up!

**Comment by polyanskiy** [comment]
First entry removed. Thanks!
