### ISSUE TITLE
Extinction coefficient computation from AGF transmission data

### ISSUE THREAD

**Issue by ashishUthama** [polyanskiy/refractiveindex.info-database#51]
For this glass:
https://refractiveindex.info/?shelf=glass&book=HIKARI-SF&page=J-SFH1

at 1um, the website lists Extinction coefficient as k = 5.5900e-8.
Which comes from:  data-nk/glass/hikari/J-SFH1.yml, whose snipped content is:

```
  - type: tabulated k
    data: |
        <...>
        1.000 5.5900E-08
```

The corresponding glass from 
    https://www.hikari-g.co.jp/optical_glass/catalog/document/HIKARI_Catalog.pdf (Page 107)
has this in the transmission table:
`  1.0000    0.9950   10.0000`

[agf2yml](https://github.com/polyanskiy/refractiveindex.info-scripts/blob/master/agf2yml/agf2yml.py) has this formula:
```
            k = -float(gd.wl[i]) / (4*math.pi) * \
                math.log(float(gd.IT[i])) / (float(gd.thickness[i])*1000)
```

Which gives:
```
>>> -float(1) / (4*math.pi) * math.log(float(0.9950)) / (float(10)*1000)
3.9888540433596814e-08
```

What is causing this difference in extinction coefficient values in the site vs (my interpretation) of the code?

**Comment by polyanskiy** [comment]
Older version of HIKARI catalog https://refractiveindex.info/download/data/2017/hikari_2017-04-01.pdf listed internal transmission of 10-mm J-SFH1 as 0.993. I am planning to update optical glass information some time in the next few months.
