### ISSUE TITLE
More fused silica data

### ISSUE THREAD

**Issue by kitchenknif** [polyanskiy/refractiveindex.info-database#9]
Found this paper that reviews a ton of experimental Fused silica refractive indexes, ranging form hard UV to deep IR. 
I might get around to formatting some of this data, but not sure when.

https://www.osapublishing.org/ao/abstract.cfm?uri=ao-46-33-8118

**Comment by polyanskiy** [comment]
Authors claim that digital data is available upon request. May be worth asking.

**Comment by kitchenknif** [comment]
I implemented the gaussian function based refractive index / extinction coefficient formula and it works nicely.
Also they say that the Malitson formula (eq. 20 in the paper) has been shown to work for a wider range than originally intended - to around 6.7mkm, up from the current 3.71mkm
